In [10]:
#Ex 1 Import the numpy package under the name np (★☆☆)

import numpy as np


In [13]:
#Ex2 Print the numpy version and the configuration (★☆☆)

np.version.version

'1.19.2'

In [14]:
#Ex 3 Create a null vector of size 10 (★☆☆)

a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:


a[5]=2
print(a)

[0. 0. 0. 0. 0. 2. 0. 0. 0. 0.]


In [160]:
#Ex 4 How to find the memory size of any array (★☆☆)

print("%d" %(a.size))

print("%d" %(a.itemsize))


10
8


In [24]:
#Ex 5  How to get the documentation of the numpy add function from the command line? (★☆☆)

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [80]:
#Ex 6  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

x=np.zeros((10,1))
x[:]=np.nan
x[5]=1
print(x)

[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 1.]
 [nan]
 [nan]
 [nan]
 [nan]]


In [163]:
#Ex 7 Create a vector with values ranging from 10 to 49 (★☆☆)

y=np.arange(10,49)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [164]:
#Ex 8  Reverse a vector (first element becomes last) (★☆☆)

w=y[::-1]
print(w)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [35]:
#Ex 9 Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

z=np.arange(0,9)
z=z.reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
#Ex 10 Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

a=[1,2,0,0,4,0]
a=np.nonzero(a)
print(a)

(array([0, 1, 4], dtype=int64),)


In [40]:
#Ex 11 Create a 3x3 identity matrix (★☆☆)

a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
#Ex 12 Create a 3x3x3 array with random values (★☆☆)

a=np.random.random((3,3,3))
print("array",a)

array [[[0.19969284 0.05230116 0.20361244]
  [0.84000592 0.56144947 0.15925622]
  [0.95246209 0.56209634 0.13036285]]

 [[0.51380617 0.01680088 0.78671391]
  [0.78497956 0.77705406 0.98658203]
  [0.09417816 0.75678205 0.53791549]]

 [[0.86060857 0.75454577 0.22787523]
  [0.76857276 0.17392049 0.12054819]
  [0.63904778 0.0848775  0.13592403]]]


In [46]:
#Ex 13 Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

a=np.random.random((10,10))
max=a.max()
min=a.min()
print(max, min)

0.9972333783329769 0.01804091666766794


In [49]:
#Ex 14 Create a random vector of size 30 and find the mean value (★☆☆)
a=np.random.random(30)
#print(a)
mean_value= a.mean()
print(mean_value)

0.5967507761529784


In [58]:
#Ex 15. Create a 2d array with 1 on the border and 0 inside

x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [82]:
#Ex 16 How to add a border (filled with 0's) around an existing array? (★☆☆)

x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
#Ex 17 What is the result of the following expression? (★☆☆)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

False

In [102]:
#Ex 18 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#i=np.zeros(5)
m=[1,2,3,4]
j=np.diag(m, k=-1)
j

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [165]:
#Ex 19 Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

a = np.zeros((8,8), dtype=int)
a[1::2, ::1]= 1
a[::1, 1::2] = 1
print (a)



[[0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]]


In [115]:
# Ex 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

p=np.random.random((6,7,8))
#print(p)

print (np.unravel_index(99, (6,7,8)))

(1, 5, 3)


In [122]:
# Ex 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

array= np.array([[0,1], [1,0]])

print(array)
Z = np.tile(array,(4,4))
Z

[[0 1]
 [1 0]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [129]:
#Ex. 22 Normalize a 5x5 random matrix (★☆☆)

d=np.random.random((5,5))
std=np.std(d)
mean_=np.mean(d)
w=(d-mean_)/std
print(w)

[[-0.50168219  0.72826628  1.40851863 -0.54749294  1.12317633]
 [ 1.58555954 -0.47225103  0.14075278  1.21597941  1.16720067]
 [-1.53920521 -0.07139878 -0.56937661 -0.99207527 -1.61825973]
 [-0.61250202  1.78852057  0.02561804 -0.16565916  0.50732657]
 [-0.80007463 -1.53917574 -0.55078122 -0.73860645  1.02762212]]


In [136]:
#Ex 24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

a= np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
